### PR TITLE
Code review improvements implemented

### PR DESCRIPTION
**Pull request by olehpovshednyi**
This PR implements the majority of improvements based on the latest code review for the project.

### CODE REVIEW

**Comment by ygerasimov** [comment]
@olehpovshednyi this code fails on the attached job. Please test as well.

The error I am getting is:
```
j:1140-p:30-b:1200-u:https://vrt-test.diffy.website Error: Evaluation failed: ReferenceError: getPosition is not defined
    at vrtPaintOver (pptr://__puppeteer_evaluation_script__:5:28)
    at pptr://__puppeteer_evaluation_script__:39:15
    at NodeList.forEach (<anonymous>)
    at pptr://__puppeteer_evaluation_script__:38:14
    at Array.forEach (<anonymous>)
    at pptr://__puppeteer_evaluation_script__:33:17
    at ExecutionContext._ExecutionContext_evaluate (/diffy-worker/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)
    at async ExecutionContext.evaluate (/diffy-worker/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)
    at async Object.perform (/diffy-worker/lib/funcPerform.js:516:7)
    at async Executor.run (/diffy-worker/lib/executor.js:33:16)
    at async run (/diffy-worker/index.js:167:20)
    at async /diffy-worker/index.js:109:15
```

[screenshot2.json](https://github.com/user-attachments/files/16729944/screenshot2.json)

**Comment by olehpovshednyi** [comment]
I fixed the issue and checked it with the provided script while adding the script to test jobs in the project. Additionally, I migrated AWS from v2 to v3 and implemented all the related changes.

**Comment by ygerasimov** [comment]
I ran screenshots (`node --env-file=.env index.js --file=test_jobs/screenshot3.json`) and got an error:
```
error: Fail Send SQS Message to sendSQSResult CredentialsProviderError: Could not load credentials from any providers
    at /diffy-worker/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js:136:13
    at /diffy-worker/node_modules/@smithy/property-provider/dist-cjs/index.js:97:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (/diffy-worker/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18)
    at async /diffy-worker/node_modules/@smithy/property-provider/dist-cjs/index.js:142:18
    at async /diffy-worker/node_modules/@smithy/core/dist-cjs/index.js:82:17
    at async /diffy-worker/node_modules/@aws-sdk/middleware-sdk-sqs/dist-cjs/index.js:131:16
    at async /diffy-worker/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22 {
  tryNextLink: false
}
```

If we run screenshots from a file -- there is no need to upload results to SQS at all.

**Comment by olehpovshednyi** [comment]
Important note: to make new version of AWS library pick up the credentials from the `.env` file automatically, you need to rename your variables in the `.env` file: 
`S3_ACCESS_KEY_ID `-> `AWS_ACCESS_KEY_ID`
`SE_ACCESS_KEY_SECRET` -> `AWS_SECRET_ACCESS_KEY`

**Pull request merged**
